---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster
  become: true

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ master_ip }}:6443
  register: join_cluster
  notify:
    - Recreate kube-dns
  become: true

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: join_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: false
  become: true

- name: Clean up ROOT directory
  when: join_cluster is succeeded
  file:
    path: "/root/.kube"
    state: absent
  become: true

- name: Create ROOT's kube directory
  file:
    path: "/root/.kube/"
    state: directory
  become: true

- name: Copy admin.conf to ROOT directory
  when: join_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "/root/.kube/config"
    mode: 0755
    remote_src: false
  become: true
