---
  - block:
    - name: Configure route
      shell: python config-route.py
      args:
        chdir: "{{ sona_cni_tmp_dir }}"
      retries: 5
      delay: 3
      register: result
      until: result.rc == 0

    - name: Restart OVS daemon
      service:
        name: openvswitch-switch
        state: restarted
      become: true  

    - name: Remove SONA-CNI tmp directory
      file:
        state: absent
        path: "{{ sona_cni_tmp_dir }}/"
      become: true

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
