---
  - block:
    - name: Configure route
      shell: python config-route.py
      args:
        chdir: "{{ sona_cni_tmp_dir }}"
      ignore_errors: yes

    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
