---
  - block:
    - name: "Install pip"
      apt:
        name: "python-pip"
        state: installed
      become: true

    - name: "Install git"
      apt:
        name: "git"
        state: installed
      become: true

    - name: "Clone SONA-CNI"
      git:
        repo: "{{ sona_cni_repo }}"
        dest: "{{ sona_cni_tmp_dir }}"

    - name: "Install python dependencies"
      pip:
        requirements: "{{ sona_cni_tmp_dir }}/requirements.txt"

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
