---
  - block:
    - name: Add EPEL repository
      yum:
        name: epel-release
        state: installed
      become: true

    - name: Install pip
      yum:
        name: python-pip
        state: installed
      become: true
    
    - name: Install git
      yum:
        name: git
        state: installed

    - name: Install net-tools
      yum:
        name: net-tools
        state: installed

    - name: Clone SONA-CNI
      git:
        repo: "{{ sona_cni_repo }}"
        dest: "{{ sona_cni_tmp_dir }}"

    - name: Install python dependencies
      pip:
        requirements: "{{ sona_cni_tmp_dir }}/requirements.txt"
    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
