---
  - block:
    - name: Add Kubernetes yum repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes Repository
        file: kubernetes
        baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: no
    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
