---

- hosts: cluster
  gather_facts: no
  become: yes
  tasks:
    - name: "Reset Kubernetes component"
      shell: "kubeadm reset --force"
      ignore_errors: True
    - name: "Reset external bridge IP"
      shell: "ip addr add $(ip -4 addr show kbr-ex | grep -oP '(?<=inet\\s)\\d+(\\.\\d+){3}')/24 dev {{ external_interface }}"
      ignore_errors: True
    - name: "Reset OpenvSwitch"
      shell: |
        ovs-vsctl del-br kbr-int
        ovs-vsctl del-br kbr-ex
      ignore_errors: True
