---
- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: ovs, tags: ovs }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm
    - name: "Healthcheck role"
      include_role:
        name: healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

- hosts: worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/worker, tags: worker }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/clean/master, tags: clean }

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/clean/node, tags: clean }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubesona, tags: kubesona }
