---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: ovs, tags: ovs }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
