---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: ovs, tags: ovs }
    - { role: cni, tags: cni }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }

- hosts: worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/worker, tags: worker }
