---
- name: set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yml

- name: Set fact based on OS
  set_fact:
    ovs_dir: "{{ el_dir }}"
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Download OVS
  get_url:
    url: "{{ ovs_url }}"
    dest: /tmp/

- name: Install Generic OVS dependencies
  package:
    name: "{{ item }}"
    state: installed
  become: true
  with_items: "{{ generic_deps }}"

- include_tasks: el_prep.yml
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- include_tasks: el_install.yml
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
