---
  - block:
    - name: "Remove kubelet"
      apt:
        name: kubelet
        state: absent
    - name: "Remove kubeadm"
      apt:
        name: kubeadm
        state: absent

    - name: "Remove kubectl"
      apt:
        name: kubectl
        state: absent

    - name: "Remove dependencies that are no longer required"
      apt:
        autoremove: yes

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
