---
  - block:
    - name: "Install OpenvSwitch (Debian/Ubuntu)"
      apt:
        name: "openvswitch-switch"
        state: present
        update_cache: yes
      become: true
      when: ansible_distribution_release != "xenial"

    - name: "Install OpenvSwitch with kernel modules (Debian/Ubuntu)"
      apt:
        deb: "{{ item }}"
        state: present
      with_items:
        - "{{deb_tmp}}/{{ovs_deb_package}}"
        - "{{deb_tmp}}/{{ovs_common_deb_package}}"
        - "{{deb_tmp}}/{{ovs_dp_dkms_deb_package}}"
        - "{{deb_tmp}}/{{ovs_dp_src_deb_package}}"
        - "{{deb_tmp}}/{{ovs_pki_deb_package}}"
        - "{{deb_tmp}}/{{ovs_vtep_deb_package}}"
        - "{{deb_tmp}}/{{ovs_python_deb_package}}"
        - "{{deb_tmp}}/{{ovs_lib_deb_package}}"
        - "{{deb_tmp}}/{{ovs_lib_dev_deb_package}}"
      become: true
      when: ansible_distribution_release == "xenial"

    - name: "Open OVSDB port"
      command: sed -i '/set ovsdb-server \"$DB_FILE\"/a \        set \"$@\" --remote=ptcp:6650' /usr/share/openvswitch/scripts/ovs-ctl
      become: true

    - name: "Start and enable OVS daemon"
      service:
        name: "openvswitch-switch"
        state: started
        enabled: yes
      become: true

    - name: "Restart OVS daemon"
      service:
        name: "openvswitch-switch"
        state: restarted
      become: true

    - name: "Probe OVS module"
      modprobe:
        name: "openvswitch"
        state: present
      become: true

    - name: "Probe VXLAN module"
      modprobe:
        name: "vxlan"
        state: present
      become: true

    - name: "Probe GENEVE module"
      modprobe:
        name: "geneve"
        state: present
      become: true

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
