---
  - block:
    - name: Apt-get update
      apt:
        update_cache: yes
        upgrade: dist
      become: true
      
    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
