---
  - block:
    - name: Yum update
      yum:
        name: '*'
        state: latest
        update_cache: yes
        exclude: kernel*, kube*
      become: true

    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
