---
# This ConfigMap is used to configure a self-hosted atomix installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: atomix-config
  namespace: kube-system
data:
  atomix.json: |-
    {
      "cluster": {
        "node": {
            "id": "atomix-1",
            "address": "127.0.0.1:5679"
        },
        "clusterId": "onos",
        "discovery": {
            "nodes": [
                {
                    "id": "atomix-1",
                    "address": "127.0.0.1:5679"
                }
            ],
            "type": "bootstrap"
        }
      },
      "partitionGroups": {
        "raft": {
            "partitionSize": 3,
            "type": "raft",
            "members": [
                "atomix-1"
            ],
            "partitions": 1
        }
      },
      "managementGroup": {
        "partitionSize": 1,
        "type": "raft",
        "members": [
            "atomix-1"
        ],
        "partitions": 1
      }
    }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomix
  namespace: kube-system
  labels:
    k8s-app: atomix
spec:
  serviceName: atomix
  selector:
    matchLabels:
      k8s-app: atomix
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      name: atomix
      namespace: kube-system
      labels:
        k8s-app: atomix
    spec:
      hostNetwork: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      nodeSelector:
        node-role.kubernetes.io/master: ""

      # These containers are run during pod initialization
      initContainers:
      - name: atomix-init
        image: busybox
        command: ["/bin/sh", "-c", "echo $ATOMIX_JSON > /tmp/atomix.json; cat /tmp/atomix.json"]
        env:
          - name: ATOMIX_JSON
            valueFrom:
              configMapKeyRef:
                name: atomix-config
                key: atomix.json
        volumeMounts:
          - name: config
            mountPath: /tmp
            readOnly: false
      containers:
      - name: atomix
        image: opensona/atomix-docker:k8s
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: -Xmx2G
        ports:
        - name: client
          containerPort: 5678
        - name: server
          containerPort: 5679
        readinessProbe:
          httpGet:
            path: /v1/status
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /v1/status
            port: 5678
          initialDelaySeconds: 60
          timeoutSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /root/atomix/config
            readOnly: true
      volumes:
      - name: config
        hostPath:
          path: /tmp/atomix-config
          type: DirectoryOrCreate
