---
  - block:
    - name: "Remove kubelet"
      apt:
        name: kubelet
        state: absent
    - name: "Remove kubeadm"
      apt:
        name: kubeadm
        state: absent

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
