---
galaxy_info:
  author: Jian Li
  description: |
    Install Kubernetes with SONA-CNI
  company: SK Telecom

  min_ansible_version: 2.1.2

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - trusty

  galaxy_tags: []

dependencies:
  - { role: kubernetes/node, pkgs: ["kubelet", "kubeadm"] }
