---
galaxy_info:
  author: Jian Li
  description: |
    Install Kubernetes with SONA-CNI
  company: SK Telecom

  min_ansible_version: 2.1.2

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags: []

dependencies:
  - { role: kubernetes/node, kube_pkgs: ["kubelet-{{ kube_version }}", "kubeadm-{{ kube_version }}", "kubectl-{{ kube_version }}"], when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat" }
  - { role: kubernetes/node, kube_pkgs: ["kubelet={{ kube_version }}-00", "kubeadm={{ kube_version }}-00", "kubectl={{ kube_version }}-00"], when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu" }
