---
  - block:
    - name: Install docker engine (Debian/Ubuntu)
      apt:
        update_cache: yes
        name: "docker-ce"
        state: present

    - name: Hold docker version
      dpkg_selections:
        name: docker-ce
        selection: hold

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
