---
  - block:
    - name: Install apt-transport-https
      apt:
        name: "apt-transport-https"
        state: present
        update_cache: yes

    - name: Add Docker APT GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: 'docker'

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
