---
  - block:
    - name: Add Docker yum repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
